Update master.yml

diff --git a/.github/workflows/master.yml b/.github/workflows/master.yml
--- a/.github/workflows/master.yml
+++ b/.github/workflows/master.yml
@@ -24,7 +24,7 @@ jobs:
           ${{ runner.os }}-maven-
       
     - name: Build with Maven
-      run: mvn -B clean package -Pproduction
+      run: ./mvnw -B clean package -Pproduction
       
     - name: Check for uncommited changes
       run: |
@@ -40,7 +40,7 @@ jobs:
           echo ----------------------------------------
           echo Troubleshooting
           echo ----------------------------------------
-          echo "::error::Unstaged changes detected. Locally try running: git clean -ffdx && mvn -B clean package -Pproduction"
+          echo "::error::Unstaged changes detected. Locally try running: git clean -ffdx && ./mvnw -B clean package -Pproduction"
           exit 1
         fi
 
@@ -58,20 +58,20 @@ jobs:
         git config --global user.name "GitHub Actions"
       
     - name: Un-SNAP root
-      run: mvn -B versions:set -DremoveSnapshot -DgenerateBackupPoms=false
+      run: ./mvnw -B versions:set -DremoveSnapshot -DgenerateBackupPoms=false
     
     - name: Un-SNAP demo
-      run: mvn -B versions:set -DremoveSnapshot -DgenerateBackupPoms=false
+      run: ./mvnw -B versions:set -DremoveSnapshot -DgenerateBackupPoms=false
       working-directory: vaadin-date-range-picker-demo
   
     - name: Un-SNAP 
-      run: mvn -B versions:set -DremoveSnapshot -DgenerateBackupPoms=false
+      run: ./mvnw -B versions:set -DremoveSnapshot -DgenerateBackupPoms=false
       working-directory: vaadin-date-range-picker
   
     - name: Get version
       id: version
       run: |
-       echo "::set-output name=release::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
+       echo "::set-output name=release::$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)"
       working-directory: vaadin-date-range-picker
   
     - name: Commit and Push
@@ -127,7 +127,7 @@ jobs:
         gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
 
     - name: Publish to Apache Maven Central
-      run: mvn deploy -Possrh
+      run: ./mvnw deploy -Possrh
       env:
         MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
         MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
@@ -152,7 +152,7 @@ jobs:
         java-version: 1.8
       
     - name: Build for Vaadin Directory
-      run: mvn -B install -Pdirectory
+      run: ./mvnw -B install -Pdirectory
       working-directory: vaadin-date-range-picker
       
     - name: Upload asset
@@ -165,7 +165,7 @@ jobs:
     - name: Get version
       id: version
       run: |
-       echo "::set-output name=release::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
+       echo "::set-output name=release::$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)"
       working-directory: vaadin-date-range-picker
 
     - name: Upload Release Asset
@@ -205,7 +205,7 @@ jobs:
           ${{ runner.os }}-maven-:  
 
     - name: Build dependencies/licenses files
-      run: mvn -B project-info-reports:dependencies
+      run: ./mvnw -B project-info-reports:dependencies
       working-directory: vaadin-date-range-picker
 
     - name: Upload licenses - Upload Artifact
@@ -252,14 +252,14 @@ jobs:
         git pull
         
     - name: Inc Version and SNAP root
-      run: mvn -B build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion} -DgenerateBackupPoms=false -DnextSnapshot=true
+      run: ./mvnw -B build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion} -DgenerateBackupPoms=false -DnextSnapshot=true
     
     - name: Inc Version and SNAP demo
-      run: mvn -B build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion} -DgenerateBackupPoms=false -DnextSnapshot=true
+      run: ./mvnw -B build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion} -DgenerateBackupPoms=false -DnextSnapshot=true
       working-directory: vaadin-date-range-picker-demo
   
     - name: Inc Version and SNAP 
-      run: mvn -B build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion} -DgenerateBackupPoms=false -DnextSnapshot=true
+      run: ./mvnw -B build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion} -DgenerateBackupPoms=false -DnextSnapshot=true
       working-directory: vaadin-date-range-picker
 
     - name: Git Commit and Push
