Updated workflows :cactus:

diff --git a/.github/workflows/master.yml b/.github/workflows/master.yml
--- a/.github/workflows/master.yml
+++ b/.github/workflows/master.yml
@@ -5,9 +5,48 @@ on:
     branches: [ master ]
 
 jobs:
+  check_code: # Validates the code (see develop.yml)
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v2
+      
+    - name: Set up JDK 1.8
+      uses: actions/setup-java@v1
+      with:
+        java-version: 1.8
+
+    - name: Cache local Maven repository
+      uses: actions/cache@v2
+      with:
+        path: ~/.m2/repository
+        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+        restore-keys: |
+          ${{ runner.os }}-maven-
+      
+    - name: Build with Maven
+      run: mvn -B clean package -Pproduction
+      
+    - name: Check for uncommited changes
+      run: |
+        if [[ "$(git status --porcelain)" != "" ]]; then
+          echo ----------------------------------------
+          echo git status
+          echo ----------------------------------------
+          git status
+          echo ----------------------------------------
+          echo git diff
+          echo ----------------------------------------
+          git diff
+          echo ----------------------------------------
+          echo Troubleshooting
+          echo ----------------------------------------
+          echo "::error::Unstaged changes detected. Locally try running: git clean -ffdx && mvn -B clean package -Pproduction"
+          exit 1
+        fi
+
   prepare_release:
     runs-on: ubuntu-latest
-
+    needs: [check_code]
     steps:
     - uses: actions/checkout@v2
       
@@ -49,6 +88,7 @@ jobs:
       with:
         tag_name: v${{ steps.version.outputs.release }}
         release_name: v${{ steps.version.outputs.release }}
+        commitish: v${{ steps.version.outputs.release }} #Use the current tag here
         body: |
           ## Installation
           Add the following lines to your pom:
@@ -156,6 +196,67 @@ jobs:
         asset_path: vaadin-date-range-picker/target/vaadin-date-range-picker-${{ steps.version.outputs.release }}.zip
         asset_name: vaadin-date-range-picker-${{ steps.version.outputs.release }}.zip
         asset_content_type: application/zip
+
+  publish-pages:
+    name: Publish dependencies and licenses to github pages
+    runs-on: ubuntu-latest
+    needs: [prepare_release]
+    steps:
+    - uses: actions/checkout@v2
+      
+    - name: Init Git and pull
+      run: |
+        git config --global user.email "actions@github.com"
+        git config --global user.name "GitHub Actions"
+        git pull
+
+    - name: Setup - Java
+      uses: actions/setup-java@v1
+      with:
+        java-version: 1.8
+
+    - name: Restore - Maven Cache
+      uses: actions/cache@v1
+      with:
+        path: ~/.m2/repository
+        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+        restore-keys: |
+          ${{ runner.os }}-maven-:  
+
+    - name: Build dependencies/licenses files
+      run: mvn -B project-info-reports:dependencies
+      working-directory: vaadin-date-range-picker
+
+    - name: Upload licenses - Upload Artifact
+      uses: actions/upload-artifact@v2
+      with:
+        name: dependencies-licenses
+        path: vaadin-date-range-picker/target/site
+
+    - name: Generate docs/dependencies dir
+      run: mkdir -p docs/dependencies
+
+    - name: Move built files into docs/dependencies
+      run: mv vaadin-date-range-picker/target/site/* docs/dependencies
+
+    - name: Rename dependencies.html to index.html
+      working-directory: docs/dependencies
+      run: mv dependencies.html index.html
+
+    - name: Copy Readme into docs (as index.md)
+      run: cp README.md docs/index.md
+
+    - name: Configure Pages
+      working-directory: docs
+      run: |-
+        echo "theme: jekyll-theme-tactile" > _config.yml
+
+    - name: Deploy to Github pages
+      uses: peaceiris/actions-gh-pages@v3
+      with:
+        github_token: ${{ secrets.GITHUB_TOKEN }}
+        publish_dir: ./docs
+        enable_jekyll: true
 
   after_release:
     runs-on: ubuntu-latest
